// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCafTolzJ5RAThJxtUCaQEF0rN27TXJjCo',
    appId: '1:799665181957:web:c818ec5162500da3e4936c',
    messagingSenderId: '799665181957',
    projectId: 'intern-trip',
    authDomain: 'intern-trip.firebaseapp.com',
    storageBucket: 'intern-trip.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeInxua0FzT-nHleptIVyPGaqbN8HrQY0',
    appId: '1:799665181957:android:ed6970b6b1bb9d10e4936c',
    messagingSenderId: '799665181957',
    projectId: 'intern-trip',
    storageBucket: 'intern-trip.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuOdSgqyURnLjrcCBx6tUqlIfYfh81Upw',
    appId: '1:799665181957:ios:54e5f5d76f3037e2e4936c',
    messagingSenderId: '799665181957',
    projectId: 'intern-trip',
    storageBucket: 'intern-trip.appspot.com',
    iosClientId: '799665181957-3q22dh81fjc7h8r5rr73fs20qs0rckuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.internTrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuOdSgqyURnLjrcCBx6tUqlIfYfh81Upw',
    appId: '1:799665181957:ios:54e5f5d76f3037e2e4936c',
    messagingSenderId: '799665181957',
    projectId: 'intern-trip',
    storageBucket: 'intern-trip.appspot.com',
    iosClientId: '799665181957-3q22dh81fjc7h8r5rr73fs20qs0rckuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.internTrip',
  );
}
